### ISSUE TITLE
Figure 2 replication

### ISSUE THREAD

**Issue by yannadani** [TrentBrick/PyTorchDiscreteFlows#2]
Hi,

I was able to more or less get the reproduction of the second figure. It looks something like this:
![download (1)](https://user-images.githubusercontent.com/11159992/86412818-0dd49600-bcc0-11ea-8164-b1a421eaa0c5.png)
I guess minor differences are due to different hyperparameters.

Thanks for your code. I guess the main issue was that one_hot_add implementation was missing (as one_hot_add and one_hot_minus are exactly the same in your current version). I have corrected it in my [fork](https://github.com/yannadani/DiscreteFlows), and have added some tests to cross-check with tf implementation. I have not tested with MADE network or bipartite case, but hopefully should work.

**Comment by TrentBrick** [comment]
@yannadani thanks for this and that is great news. I will take a look at your fork. 

Do note that my one_hot_add and one_hot_minus are not exactly the same. The one_hot_add function has an additional transpose in it (line 137 of disc_utils.py) that I previously debugged and thought was working (I remember not being able to use the fft() and ifft() functions with pytorch back in December when I was first porting the code over from tensorflow and finding this transpose as a work around... not sure if fft has been added since or I previously missed something).

**Comment by TrentBrick** [comment]
@yannadani I have cloned and looked at your repo. A few things: 

1. I have pushed a testing script for my one_hot_add and yours. They look to give the same result but mine is marginally faster. I have put a self contained example in a new directory testing_scripts. Let me know if I am wrong on this. 

2. For good measure I tried your one_hot_add with my Fig2 replication but it also didn't change my results. 

3. I then tried the replication notebook in your repo and got a result that looks pretty similar to the image you have shared. 

4. I took the Embedding Network layer cell from your notebook and tried it with my codebase and Fig2 Replication plotting etc. and I think I can reproduce it also! Now to figure out why this layer is working when my bipartite and autoregressive ones are not... 

Thanks again for all of this and I will be sure to give you credit.

**Comment by yannadani** [comment]
Oops my bad about your one hot add implementation then. The other difference was when you go from z to X you need to flip the inputs I believe when using an embedding network. Not sure how that would work with made network though.

**Comment by TrentBrick** [comment]
Can you provide the code line where there is an error with the embedding network for flipping the inputs? I use `if self.parity:` on line 287 and 319. Also for a single flow this should not matter?

**Comment by TrentBrick** [comment]
I found the input flip you were referring to inside the training loop but I dont think it makes any difference. I have just pushed code integrating your notebook and replication with mine. I have also taken your utils.py because your one_hot function was much faster -- thanks for this. I have tried to acknowledge you in a few places, please let me know how else I can.

I have also updated the TODOs. Getting the MADE network to work and then reproducing more of the Figures are the big ones. Would love to have your help with these if you have the time/interest.

**Comment by yannadani** [comment]
No problem. Thanks a lot for your code, its most of the base anyway. Do not worry about acknowledgements, as I just do it as an enthusiast and as part of my project. The current acknowledgement is more than sufficient. 

I am actually looking into replacing the embedding network as it does not scale (more than 30 dimensions) and runs into memory issues. So I will definitely need the MADE network and can look it up try to get it working. I would definitely be happy to help on made network. For the bipartite case, I am not really sure of the details, and have no much idea. But can always give a try, if I have time at that point. 

My strategy so far is to get an implementation as close to the tensorflow as possible, even if they are minor heuristics (as many times these turn out to be crucial in getting the results). So I used this flip, embedding network and everything as they have done. The next is the MADE. I'll look into it this weekend. Can you let me know which part is exactly broken in pytorch's case, as compared to the edward MADE network, in case you have already pinned it down?

**Comment by TrentBrick** [comment]
I think it’s good to not deviate from the TF implementation where it can be avoided. All of my code was written before the mixture of gaussians example was public (that was only released through correspondence with the authors) and so there was more deviation than I would have otherwise liked.

I actually got ahead of myself and have ported over the MADE network from Edward2 and it looks to be working! Definitely double check my implementation and testing script though.

I think the next step is to implement the sink horn and Potts model along with ensuring the scaling output works. Let me know if you’d be interested in those or something I’m missing :)

**Comment by yannadani** [comment]
I can look into sink horn in a couple of days. Also, do you know why the figure 2 is still not as good as in the paper?

**Comment by TrentBrick** [comment]
Sounds great @yannadani . And from running the MADE network, I am getting the impression that the results are quite initialization dependent. Some of the results have looked just as good or better than the paper figure 2 I think.
